name: covidfree
description: MOPH Covidfree.

publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^8.1.6
  fluttertoast: ^8.0.8
  http: ^0.13.3
  qr_code_scanner: ^0.5.2
  dio: ^4.0.0
  loader_overlay: ^2.0.2+1
  flutter_rounded_date_picker: ^2.0.2
  pretty_dio_logger: ^1.1.1
  url_launcher: ^6.0.11
  flutter_secure_storage: ^4.2.1
  jwt_decode: ^0.3.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/stopcovid_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Prompt
      fonts:
         - asset: assets/fonts/Prompt-Medium.ttf
    - family: Kanit
      fonts:
         - asset: assets/fonts/Kanit-Regular.ttf
